spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

#  profiles:
#    active: setup
server:
  port: 8081