spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
jwt:
  secret: default_secret_key_which_should_be_very_long_in_production
  access-token-expiration: 1000  # 1 seconds
  refresh-token-expiration: 5000 # 5 seconds
