spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

#  profiles:
#    active: setup
app:
  setup:
    roles: "STUDENT, TEACHER, SUPER_ADMIN" # Default roles

jwt:
  secret: ${JWT_SECRET:default_secret_key_which_should_be_very_long_in_production}
  access-token-expiration: 3600000  # 1 hour
  refresh-token-expiration: 86400000 # 24 hours
