spring:
  application:
    name: client-auth-service
  datasource:
    url: jdbc:postgresql://localhost:10001/auth_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
#  profiles:
#    active: setup
app:
  setup:
    roles: "STUDENT, TEACHER, SUPER_ADMIN" # Default roles